language: node_js
node_js:
  - "4.1"
before_install:
  - dpkg -i http://graphviz.org/pub/graphviz/stable/ubuntu/ub12.04/x86_64/graphviz_2.38.0-1~precise_amd64.deb
before_script:
  - npm install -g gulp
  - npm install -g gitbook-cli
script:
  - gulp build
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
