language: node_js
node_js:
  - "4.1"
before_install:
  - sudo apt-get install graphviz graphviz-doc
before_script:
  - npm install -g gulp
  - npm install -g gitbook-cli
script:
  - gulp build
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
