language: node_js
node_js:
  - "6.0"
before_install:
  - sudo apt-get install graphviz graphviz-doc
before_script:
  - npm run init
  - npm run restore
script:
  - gulp build
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  except:
    - release
